[project]
org-name= "kanishka"
version= "0.1.0"

[dependencies]

[platform]
target="java11"

[[platform.libraries]]
path="./src/customer_service_extended/resources/mysql-connector-java-8.0.18.jar"
modules=["customer_service_extended"]

